# Generated by Django 4.1.3 on 2022-12-05 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("healthbutler", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "foodtype",
                "verbose_name_plural": "foodtypes",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=25)),
                ("password", models.CharField(max_length=30)),
                ("year", models.IntegerField()),
            ],
        ),

    ]
