# Generated by Django 4.1.3 on 2022-12-06 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("healthbutler", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foodtypes",
            options={
                "ordering": ("name",),
                "verbose_name": "fcategory",
                "verbose_name_plural": "fcategories",
            },
        ),
        migrations.CreateModel(
            name="Foods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(default="", max_length=200)),
                ("serving", models.CharField(max_length=200)),
                ("calories", models.PositiveIntegerField()),
                ("fat", models.PositiveIntegerField()),
                ("carbs", models.PositiveIntegerField()),
                ("fiber", models.PositiveIntegerField()),
                ("protein", models.PositiveIntegerField()),
                (
                    "fcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food",
                        to="healthbutler.foodtypes",
                    ),
                ),
            ],
            options={"ordering": ("name",), "index_together": {("id", "slug")},},
        ),
    ]
