# Generated by Django 4.1.3 on 2022-12-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthbutler", "0005_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Userinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=16)),
                ("passwd", models.CharField(max_length=32)),
                ("weight", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
            ],
        ),

    ]
